### PR TITLE
Like

### PR DESCRIPTION
**Pull request by saketkum11**
- liked page 
- 3 api call

### CODE REVIEW

**Review by shraddha15-creator — APPROVED** [review]
Good that you made small components 
good naming convention 
Well structured

**Review by Sharmaryan — APPROVED** [review]
only a small suggestion, if you are importing from the same folder, e.g. components, then make a index.js file and import from there only that will look clean

**Comment by Sharmaryan** [comment]
i am not able to create playlist, check the functionality

**Comment by saketkum11** [comment]
sure you can check now its work.

**Pull request merged**
